# Utiliser une image de base Python
FROM python:3.9-slim

# Définir le répertoire de travail
WORKDIR /app

# Installer Gunicorn et les dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn

# Copier les fichiers backend Flask dans le conteneur
COPY . .

# Exposer le port utilisé par Gunicorn
EXPOSE 5001

# Commande pour démarrer Flask avec Gunicorn
CMD ["gunicorn", "--workers=3", "--threads=2", "--bind", "0.0.0.0:5001", "main:app"]
